### ISSUE TITLE
Batch Editing Media

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#118]
@tladesignz 

![Batch Edit Media-Workflow](https://user-images.githubusercontent.com/36669955/58352228-954ea500-7e30-11e9-8d50-376306542421.jpg)

**Comment by kckthx** [comment]
Batch Edit Icon:
https://github.com/OpenArchive/openarchive-assets/blob/master/icons/batchedit.svg

**Comment by foundscapes** [comment]
Tried on both iphone6s and ipad mini - multi-select worked, but the (tiny!) multi edit button did nothing. @tladesignz 


Also, we'll need an initial popup to let people know about this feature: To edit multiple items, press and hold each.

**Comment by tladesignz** [comment]
> Tried on both iphone6s and ipad mini - multi-select worked, but the (tiny!) multi edit button did nothing. @tladesignz

I just released the latest TestFlight.

> (tiny!) multi edit button

I'll use a similar iOS system icon which will look better.

> Also, we'll need an initial popup to let people know about this feature: To edit multiple items, press and hold each.

I'll add something similar as with the flagging hint.

**Comment by foundscapes** [comment]
I can bulk edit now, but it's not very intuitive when I'm done. The only way to get back to the preview batch edit screen from metadata fields is to hit "return" on the keyboard. 

I instinctively tapped on the photos to take me out of the metadata editing fields, but it didn't work. Can we add a more obvious action here? Happy to help with UI.

**Comment by foundscapes** [comment]
More UI feedback:

When in Preview or Edit view before uploading, it's not clear which media are videos and which are photographs

**Comment by foundscapes** [comment]
Also, when done editing media in preview screen, it's a bit confusing: I can click " < Preview" in the top left to get back, and it saves everything, but that's not clear and feels like a risky click

**Comment by foundscapes** [comment]
When i add new media to be uploaded after the previous batch edit had uploaded, the previous tags are in place of blank/actual location metadata tags

**Comment by foundscapes** [comment]
confusing UI
the files under "ready to upload" have already been uploaded, so it's unclear what will be uploaded and what won't
![IMG_2933](https://user-images.githubusercontent.com/2231711/60844060-1cf83500-a18d-11e9-8f6a-0a485b082e15.PNG)

**Comment by foundscapes** [comment]
Is it possible to have a "select all" button for batch edits/uploads?

**Comment by tladesignz** [comment]
I'll try to answer these random thoughts below. However, I would very much appreciate it, if you would first structure your feedback and contemplate about where, to whom and how you address them instead of just dropping them somewhere the moment they came to your mind. Thanks.

> I can bulk edit now, but it's not very intuitive when I'm done. The only way to get back to the preview batch edit screen from metadata fields is to hit "return" on the keyboard.
> I instinctively tapped on the photos to take me out of the metadata editing fields, but it didn't work.

That's interesting. Unfortunately I can't reproduce this, as I actually stumbled over that problem myself during development and am positively sure to have added a tap handler which closes the keyboard when you tap outside the entry fields. E.g. tapping the images does work. Swiping them, though, obviously not. Tapping another field also not, of course.

> Can we add a more obvious action here? Happy to help with UI.

The original iOS-y way is to provide a "Done" button in the top right corner. A newer way, which is unfortunately some more effort, is to provide a keyboard toolbar with a "Done" button.
I'll add the first for now.

> When in Preview or Edit view before uploading, it's not clear which media are videos and which are photographs

I recommend discussing this with the people responsible for UX design. I don't think, that it's obvious anywhere and should be tackled in a broader fashion, not just here. I suggest to keep an eye on budget, though. Obvious ideas like "make it playable on tap" are probably out of said budget.

> Also, when done editing media in preview screen, it's a bit confusing: I can click " < Preview" in the top left to get back, and it saves everything, but that's not clear and feels like a risky click

As per UI guidelines of iOS and MacOS, apps should normally just save stuff, so the user doesn't loose anything.
Also, this is exactly as per provided design template. And this also happens anywhere else around the app.

> Is it possible to have a "select all" button for batch edits/uploads?

I don't know what's meant by this, but I *do* feel, that this should be its own issue, not a comment here.

> When i add new media to be uploaded after the previous batch edit had uploaded, the previous tags are in place of blank/actual location metadata tags. I could not reproduce this on the iphone or ipad mini

I'll research this.

**Comment by tladesignz** [comment]
> > When i add new media to be uploaded after the previous batch edit had uploaded, the previous tags are in place of blank/actual location metadata tags. I could not reproduce this on the iphone or 
ipad mini

> I'll research this.

Sorry, can't reproduce.
If you encounter this again, please create a new issue, write down the *exact* steps to reproduce and at best provide the content, with which it happened. Thanks!

**Comment by foundscapes** [comment]
> I'll try to answer these random thoughts below. However, I would very much appreciate it, if you would first structure your feedback and contemplate about where, to whom and how you address them instead of just dropping them somewhere the moment they came to your mind. Thanks.

I thought using this issue to address issues with this feature was structured enough, sorry it's not formatted the way you need, but we did intensive QA and UI testing yesterday and it needed to be expediently relayed.
> 
> > I can bulk edit now, but it's not very intuitive when I'm done. The only way to get back to the preview batch edit screen from metadata fields is to hit "return" on the keyboard.
> > I instinctively tapped on the photos to take me out of the metadata editing fields, but it didn't work.
> 
> That's interesting. Unfortunately I can't reproduce this, as I actually stumbled over that problem myself during development and am positively sure to have added a tap handler which closes the keyboard when you tap outside the entry fields. E.g. tapping the images does work. Swiping them, though, obviously not. Tapping another field also not, of course.

This is working now on both devices, however there is one UI issue:
the multiple edit icon is now just one square, instead of many. It looks good larger, but perhaps there is one with the many squares (like you had before) to indicate multiple editing that is also larger?

> 
> > Can we add a more obvious action here? Happy to help with UI.
> 
> The original iOS-y way is to provide a "Done" button in the top right corner. A newer way, which is unfortunately some more effort, is to provide a keyboard toolbar with a "Done" button.
> I'll add the first for now.

Ok, thanks
> 
> > When in Preview or Edit view before uploading, it's not clear which media are videos and which are photographs
> 
> I recommend discussing this with the people responsible for UX design. I don't think, that it's obvious anywhere and should be tackled in a broader fashion, not just here. I suggest to keep an eye on budget, though. Obvious ideas like "make it playable on tap" are probably out of said budget.

Ok.
> 
> > Also, when done editing media in preview screen, it's a bit confusing: I can click " < Preview" in the top left to get back, and it saves everything, but that's not clear and feels like a risky click
> 
> As per UI guidelines of iOS and MacOS, apps should normally just save stuff, so the user doesn't loose anything.
> Also, this is exactly as per provided design template. And this also happens anywhere else around the app.
Ok, it may be worth working on this issue if we can find the budget, will know later today.
> 
> > Is it possible to have a "select all" button for batch edits/uploads?
> 
> I don't know what's meant by this, but I _do_ feel, that this should be its own issue, not a comment here.

Ok, I will make one.
> 
> > When i add new media to be uploaded after the previous batch edit had uploaded, the previous tags are in place of blank/actual location metadata tags. I could not reproduce this on the iphone or ipad mini
> 
> I'll research this.

Thank you it doesn't seem to be happening on either device now, so may have been resolved.

**Comment by foundscapes** [comment]
> > > When i add new media to be uploaded after the previous batch edit had uploaded, the previous tags are in place of blank/actual location metadata tags. I could not reproduce this on the iphone or
> > > ipad mini
> 
> > I'll research this.
> 
> Sorry, can't reproduce.
> If you encounter this again, please create a new issue, write down the _exact_ steps to reproduce and at best provide the content, with which it happened. Thanks!

Yes, I will if it happens again!

**Comment by tladesignz** [comment]
> the multiple edit icon is now just one square, instead of many. It looks good larger, but perhaps there is one with the many squares (like you had before) to indicate multiple editing that is also larger?

Used the proposed icon from @kckthx, enlarged it a little.

**Comment by tladesignz** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/system-icons/

**Comment by foundscapes** [comment]
@kckthx working on finding more budget so you can make this icon for us
