### ISSUE TITLE
Lines still uneven on preview server login page

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#123]
![IMG_2474](https://user-images.githubusercontent.com/2231711/60053314-62e0d380-968c-11e9-995f-17afc66c2870.PNG)

I thought we had an issue for this, but I can't find it, apologies if it's a duplicate but it's not fixed.

**Comment by tladesignz** [comment]
Yeah, just checked. This is due to insisting, that there needs to be a line at the bottom of the last row.

This is actually faked. It's a line as a footer of the "table". There is no possibility to add a divider line to the last row. It seems, the footer line moves up together with the soft keyboard.

Since this looks really ugly, I guess, you want that line gone, rather than a divider line after the last row.

Just to be clear: It's either-or. I'll remove that line now and deny any requests to add a last line until you say the opposite.

**Comment by foundscapes** [comment]
There should always be lines for all fields. It seems fine on all other forms, when you say remove the line, would it just be for this form or on all others throughout the app with lines for the last field?
@tladesignz

**Comment by tladesignz** [comment]
They need to go on all forms/tables which will trigger the keyboard.

**Comment by foundscapes** [comment]
Are you saying that you need to remove all the lower lines from all forms/tables for this to be fixed? There isn't a better solution?

**Comment by foundscapes** [comment]
@tladesignz will add an empty field below to try to solve problem
