### ISSUE TITLE
Upload Manager

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#14]
![00_oa-upload manager](https://user-images.githubusercontent.com/36669955/49614339-987fd280-f96f-11e8-929e-e833109bff9f.png)

**Comment by tladesignz** [comment]
What should happen when you delete an upload? Should it be deleted from the app altogether? Or not? But then - what's the difference from pausing it?

**Comment by cstiens** [comment]
If you cancel an upload it should be deleted from the app.

**Comment by n8fr8** [comment]
@cstiens not sure I agree with that. Upload is an action to sync your local archive to the server. Why should cancelling an upload delete it from the local archive?

**Comment by tladesignz** [comment]
Maybe not "delete" but rather "cancel" or "stop" upload?

**Comment by n8fr8** [comment]
Allow user to drag / move item up and down in the list to affect priority

**Comment by n8fr8** [comment]
essential features for dev sprint 2:

- displaying / tracking the progress of an upload
- being able to restart a failed upload

**Comment by n8fr8** [comment]
"Natty starts an upload, and leaves the app to take an incoming call. She returns to the OA app to check on the progress. It shows her the progress was made, but that it stopped due to the background progress being killed. She taps on the progress and restarts the upload by tapping a resume button/icon"

**Comment by cstiens** [comment]
> If you cancel an upload it should be deleted from the app.
>> @cstiens not sure I agree with that. Upload is an action to sync your local archive to the server. Why should cancelling an upload delete it from the local archive?

Ah. I used the wrong words. There are 4 actions in the upload manager:
* Pause 
* Resume
* Delete
* Move

So, there's not really a notion of cancelling. If it's something you want to send to your space, but not at a given time, you would pause it.

Deleting from the upload manager would delete it from the app. If we allow the user to cancel, I think we'll end up with random media hanging around in the bullpen. @n8fr8 I can't think of a case where we need to allow the user to cancel and upload, but to keep it in that app. Can you?

**Comment by tladesignz** [comment]
So, the upload manager also manages the lifecycle of an asset inside the app? Hmmm. I mean, it's good, that it's there at all, and better here than nowhere. But isn't there a better place?

Another thought: In the current designs, as I understand, the user is only able to enter the upload manager via a button on the collection header of not-fully-uploaded collections. (A collection being a group of assets added together until an upload is triggered for that group the first time.)

In certain conditions, that could mean the user needs to switch tabs and even scroll down to finally find the button to enter the upload manager.

Wouldn't it be better it was always reachable? Like from the top left corner of the main scene?

**Comment by tladesignz** [comment]
@cstiens, @kckthx How are errors conveyed to the user? How does an upload row look, that errored?

**Comment by cstiens** [comment]
@tladesignz We have a UI solution for this. Kaci will post it. But, I'm curious.. which errors would we have.

In this case where the internet gets disconnected in the middle of an upload, I believe we would want to automatically retry without putting an error in the user's face. Is that possible?

What other error cases should we handle?

**Comment by tladesignz** [comment]
There's no point in retrying, if the server doesn't accept the file. 

There is *always* the possibility of unrecoverable errors. It is way higher, than the possibility of recovery through simple retry.

Also, retrying isn't as simple, as it looks at first glance. How often? In what frequency? Should the user be able to configure this, to not impact their data plan volume too much?

For now I consider auto-retry a feature for later. It is non-trivial to implement.

**Comment by tladesignz** [comment]
First, somewhat stable implementation is ready and will be available in next TestFlight.

Please note:

While the file upload *itself* is done in background-job-independent-of-app, all the rest isn't:

- 2x check, if folder is created, if not create (up to 4 server requests)
- Write metadata file (currently created on the fly, but background upload only allowed with files sitting in the filesystem of the app)
- Tracking successful upload. (Didn't test, yet, if callback code is kept around for execution when app is left until upload is done. Probably not because of too many layers and loose coupling.)

All of this needs to go in a dedicated background thingy, which Apple allows us to have for 10 minutes or something. I'll create a ticket for it to track progress on that.

Furthermore:

- There's currently no check, if we have a network connection or not. The upload is tried. If it fails, it is set in "pause" mode.
- No auto-retries, as these need more thinking about what stop conditions there are, the frequency of them and with what function the frequency declines. I'll add a ticket for that.

Design issues:
- There's no place intended to show errors. There are errors happening. We can't ignore them. I'll add a ticket for that, too.
- There maybe needs to be a "resume all" button. However, there's already an "Edit" button in the top right corner in the implementation, to switch the table into edit mode for reordering. That's the way how it is done in iOS. No working around that. On iPad, we could add multiple buttons in the top right corner, on iPhones, that is difficult because of lacking space.
- Finished uploads are removed. The upload manager tracks *all* uploads, not just the ones from a single collection. So there's no sense in having a subtitle "x of y". Because there is no clear-cut way of telling what y actually is. So I set the text to "x left". Feel free to improve that.

**Comment by tladesignz** [comment]
This app is like a hydra! Fix one thing, 3 new come up. :-)
