### ISSUE TITLE
While using mediafire and google drive as the server, getting "Status 404 not found" error

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#150]
1. Can we use dropbox,icloud and google drive as the private server?

2. Mediafire is the cloud instance and I have created the account for the same. But when I use it as the private server (or google drive as the private server), I am getting "Status 404 not found" error when I try to login

3, I am able to login to icloud as the private server with my login credentials , but not able to upload any media file to the same. It shows uploading the image but not getting uploaded

**Comment by tladesignz** [comment]
> Can we use dropbox,icloud and google drive as the private server?

The app supports WebDAV capable servers and the way it currently behaves, it actually specifically targets Nextcloud and Owncloud.

Dropbox, iCloud and Google Drive don't support WebDAV as an interface directly.

> Mediafire is the cloud instance and I have created the account for the same. But when I use it as the private server (or google drive as the private server), I am getting "Status 404 not found" error when I try to login

Mediafire also doesn't support the WebDAV interface.

> 3, I am able to login to icloud as the private server with my login credentials , but not able to upload any media file to the same. It shows uploading the image but not getting uploaded

iCloud supports WebDAV insofar, as it supports CalDAV and CardDAV to work as a calendar and contacts server. Both are based on WebDAV, that's probably why it doesn't break immediately. However, it doesn't support WebDAV for standard file transfer.

@foundscapes, @kckthx that seems to be a task for you:

Obviously, we're not communicating the fact, that we only support WebDAV servers like Nextcloud and Owncloud **at all**. I guess you should think about, if that isn't a problem.

Besides, the app contains a library for WebDAV support, which also has Dropbox and Microsoft OneDriver support. We could think about supporting these, too.

However, I don't see a clear reason, why you would use our app for that instead of just using their own apps. The only benefit gained would be the metadata generation and the automated folder structure.

And would it make sense for an organization to use these, anyway? Stuff could get censored by the cloud providers and it's harder to organize sharing with the right people in the organization.

**Comment by tladesignz** [comment]
Will be contained in build 39.
