### ISSUE TITLE
Import Media when No Space is Connected

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#20]

**Comment by tladesignz** [comment]
When there's no destination defined, there cannot be an upload, can it?

**Comment by cstiens** [comment]
It would be imported into OA on your local device so that you could add it to a space later.

**Comment by tladesignz** [comment]
Ok. So we're not talking about *upload* but *import*.

So there needs to be a "null" space? Or does your concept allow not having a space? *headscratch*
Just looked at your designs again. There are labels in it like "Upload to `Landsomething in China`". So that implies, that there are projects which are existing on spaces. Or cannot exist without one, since otherwise, no upload would be possible.

Maybe the labels should be rephrased? I guess it would be a good idea to keep the words "upload" and "import" strongly separated, as they are representing two very different concepts...

**Comment by n8fr8** [comment]
I agree we are confusing the terms "upload" and "import". I think that also we are confusing the terms "Connected" and "Defined".

@cstiens when you say "Connected" are you talking about being offline?

**Comment by kckthx** [comment]
Yeah @tladesignz @n8fr8 we were referring to Importing -- thanks for catching the language difference there! So not uploading to the space, but they would just import into the app/your device.

Also @n8fr8 we were referring to "connected" as having a space set up, not necessarily "online." As if in onboarding when we have them connect to a space (server) and they tap "skip". It would make sense though that if the server were offline they would still need to be able to _import_ ;) media

**Comment by kckthx** [comment]
In reference to importing when the server is offline -- we are working on a separate workflow to move media to a project -- that could support being able to still use the app offline and organize later when there is a connection.

**Comment by tladesignz** [comment]
Regarding being able to import stuff when offline: I can vouch for that. The current version does that also. The complete app would be almost impossible not doing it like that, so no worries.

Regarding your last comment: The import-into-app part is always offline. There's no immediate uploading. So no need for special workflows. Or do I misunderstand something here?
