### ISSUE TITLE
Support deleting items locally and remote

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#39]
let's figure it out!

**Comment by n8fr8** [comment]
delete from phone gallery / local storage
remove entry/media from openarchive app
delete media from remote server

three potential actions!

**Comment by tladesignz** [comment]
As mentioned on the call yesterday: The app needs to always import assets into itself. They could even be edited during import. (e.g.: iOS provides some rudimentary UI for cropping.)

When attaining assets through the Share Extension, there's actually no knowledge, where that came from. We always get copies of files, even from the "Photos" app.

We are only able to get a reference to an original photo or video through importing it through a photo picker (be it the currently used system provided, one of the many picker projects mentioned in #15 or a self-implemented one). Currently, that reference is not stored.

As Nathan mentioned, apps cannot delete these original photos completely, but just move it to a trash can.

Due to these inconsistencies and general unsupportiveness of iOS I'd very much prefer not to spend time on that part, and leave the "Photos" app/gallery/camera roll totally to the user, as we can't make any guarantees anyway.

**Comment by foundscapes** [comment]
Can we make sure to delete items in-app?

**Comment by tladesignz** [comment]
Not sure what you want to say with that?

#40 shows designs for that. Local delete is already implemented.

**Comment by foundscapes** [comment]
Ok, but can we make sure it also deletes from this view as well?
![IMG_8763](https://user-images.githubusercontent.com/2231711/55041538-b8083d00-4fea-11e9-9f3e-6e956381876d.PNG)

**Comment by tladesignz** [comment]
Sure, if somebody comes up with a UI that makes sense.
BTW: I still suggest to give direct access to the upload manager scene from here. It can get very difficult to enter that in certain circumstances otherwise.

**Comment by foundscapes** [comment]
So we can currently delete from the manage/upload page, we also need to be able to delete after tapping on item from this screen
![IMG_9097](https://user-images.githubusercontent.com/2231711/55507456-8e639d00-560c-11e9-8f81-673e77bbc15b.PNG)

**Comment by foundscapes** [comment]
waiting on @cstiens for UI design

**Comment by kckthx** [comment]
Here's a few flows with UI of what removing would look like. I also addressed the difference in the "Remove vs. Cancel vs. Delete" language -- I took out the word "Delete" so that it doesn't imply deleting from the server -- I tried to be clear in the language on the UI.

[OA-Remove-From-Home.pdf](https://github.com/OpenArchive/openarchive-ios/files/3074214/OA-Remove-From-Home.pdf)
