### ISSUE TITLE
Preview view, Icons also initiate actions

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#50]
Referencing #41 currently, tapping in the text fields allows the user to add info, but I should also be able to tap the "location" icon to add a location.

Keyboard after typing in people who are tagged, the final button should be "DONE" instead of "Next"

**Comment by tladesignz** [comment]
> Referencing #41 currently, tapping in the text fields allows the user to add info, but I should also be able to tap the "location" icon to add a location.

Fixed.

> Keyboard after typing in people who are tagged, the final button should be "DONE" instead of "Next"

Sure I can change that, but what **behaviour** are you expecting? Currently, the next field (location) gets focus and the user can edit away on that, too. Why do you want to break that flow?

**Comment by kckthx** [comment]
@tladesignz We don't want to require the user to fill out every field, they may not want to add a location. So they would still be able to tap between the fields, but the action on the keyboard would always be **DONE**

**Comment by tladesignz** [comment]
Fine. I did it as you wanted, but I still consider this as a very bad idea:

You're actually making it just worse for the user: The keyboard can always be hidden by tapping anywhere else on the screen. Now, if the user wants to *also* add a location, they need to move their thumb up to the respective text view or - even worse - to the location button in the top right, instead of just hitting "Next".

Now they have one more option to get rid of the keyboard in one step. So you're actually deter them from entering something. And for what reason? Just to have it gone. The keyboard doesn't even cover any information.

While I'm ranting anyway: I also consider disabling the "Done" button as long as there is no entered text also a bad idea: It removes one obvious option to get rid of the keyboard after accidentally triggering its appearance.
