### ISSUE TITLE
Look into resuming HTTP uploads over WebDAV

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#53]
need to be able to resume uploads rather than restart

**Comment by tladesignz** [comment]
Currently, I'm using this library:

https://github.com/amosavian/FileProvider

There's not much choice out there, unfortunately.

**Comment by tladesignz** [comment]
Ok, because of #60, I now use Alamofire instead of the FilesProvider for the upload itself.

Alamofire is just a wrapper around [NSURLSessionTask](https://developer.apple.com/documentation/foundation/nsurlsessiontask).

To support resuming uploads, we need to check, if the file is already there, and to what extent using this:
https://github.com/amosavian/FileProvider/blob/abf68a62541a4193c8d106367ddb3648e8ab693f/Sources/WebDAVFileProvider.swift#L107-L140

Then we can write a partial file to disk (or eventually stream it) and send that together with a Content-Range header:
https://stackoverflow.com/questions/47354748/nsurlsessionuploadtask-specify-content-range

**Comment by tladesignz** [comment]
So, just tested this with my own Nextcloud server.

While the aforementioned `#attributesOfItem` check does not work, because Nextcloud hides partial uploads from the UI *and* from WebDAV access, everything looks like resuming auto-magically works out of the box.

I slowed down my network connection, uploaded a 30 MByte video from https://sample-videos.com and watched the partial upload file continuously increase on the server's file system, even when killing the app and restarting the upload multiple times.

Watched the uploaded 3 minute video afterwards and it seemed just fine.

**Comment by n8fr8** [comment]
Let's re-open so we can get more testing a bit
