### ISSUE TITLE
Multi-uploading / Bulk Uploads

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#66]
Enable multiple files to be uploaded at the same time.
Enable group editing

Also discussed, but not implemented

**Comment by tladesignz** [comment]
> Enable multiple files to be uploaded at the same time.

How many at the same time do you want? 

Note 1: It normally doesn't make sense to do more than 2 at the same time, as the available bandwidth is saturated easily and the chance of breakdowns rise exponentially, which leaves you with a lot of unfinished uploads.

Note 2: There's no auto-retry, as that is yet undefined, also. See #57 

Note 3: There's currently no resume. See #53 

> Enable group editing

And how should that UX be like? Please advice.

Note 4: It is generally a bad idea to throw 2 completely unrelated topics into one issue. Please split, when follow up!

**Comment by foundscapes** [comment]
Ok This issue is just for bulk uploads now.

I thought we'd agreed on bulk uploads a while back, but I understand the challenges.

Nicole brought up an interesting point today - what if we could package the grouped items into a .tar file or some such? From an archival standpoint this makes a lot of sense and is currently used in her workflow, but not sure how challenging it would be to implement @tladesignz, please advise!

Also we need to make sure that auto-retry and resume work!

**Comment by tladesignz** [comment]
> I thought we'd agreed on bulk uploads a while back, but I understand the challenges.

Sorry, you can dream of Jeannie but she doesn't exist.
Things take time in reality. Sometimes surprisingly little, but that always comes with a catch. Sometimes things can't be done at all or not in the expected quality because of earlier design decisions and inherent dependencies.

> Nicole brought up an interesting point today - what if we could package the grouped items into a .tar file or some such? From an archival standpoint this makes a lot of sense and is currently used in her workflow, but not sure how challenging it would be to implement @tladesignz, please advise!

This would make it worse. Instead of many files, which you can upload one-by-one in relatively short time per file, you would need to upload one really huge file, and it mostly would be make-or-break.
The longer the connection needs to be, the higher the chances get, that this will never get through.

Also, it adds a useless extra step on the receiving end.

> Also we need to make sure that auto-retry and resume work!

Sorry, but this style is not helpful.

There are reasons why this is not implemented, yet (besides time), and I laid them out for all of you to think them through together with me.

Check issues #53 and #57 and help in the discussion. If you don't know what to say, ask questions and drag the right people in.

These cannot be resolved through randomly barking orders action-movie-style.

**Comment by n8fr8** [comment]
I think we are confusing terms here. Serial one at a time uploads are fine. The current issue is the user experience. I can't ask to start the upload process for all my non-uploaded media items with one tap. I have to do it for each one.

What we are talking about is the UI from #36 where it says "9 waiting to upload" as a group, and then you can trigger all of those to be uploaded with one tap.

**Comment by n8fr8** [comment]
I see #62 was fixed, so great!

**Comment by foundscapes** [comment]
Yes @n8fr8 clarified it - serial one at a time uploads are what I meant, it would just be great to have an "upload all" feature, which I thought we'd agreed upon.

re: randomly barking orders...I am sorry if my questions were not clear @tladesignz and my tone was never meant to be read in that manner. I am just sharing feedback from our core users and asking if certain functionalities are possible.

**Comment by tladesignz** [comment]
You are confusing me...
All the stuff gets uploaded automatically as soon as one hits "Upload".
The "Upload" button in the top right corner in the scene, where one can scroll through all assets of a collection. 

It's like that, since I added the upload manager and never changed since then.

They're just not restarted automatically, when the upload breaks. Because of #57.

@foundscapes: Thanks for your apology! I know you didn't mean it that way, but nevertheless you did write it like that.

>  and asking if certain functionalities are possible.

Just to be clear: 

> Also we need to make sure that auto-retry and resume work!

That is *not* a question. That is an [imperative](https://en.wikipedia.org/wiki/Imperative_mood#English). 

Instead, maybe can we more try to work like [this](https://www.forbes.com/sites/forbeshumanresourcescouncil/2018/02/16/tomorrows-best-leaders-will-lead-with-questions-not-answers/)?

**Comment by tladesignz** [comment]
Ok, we had a long talk yesterday, and I'll close this now.

Just to reiterate:

1. There's one upload manager and it shows **all** pending uploads, always.
2. Stuff gets uploaded one after another, which is fine. And this will be done, as long as it doesn't break. What needs to be added is auto-retry, which is tracked here: #57.
3. There's a UI issue, in that there's not *one* central button to reach the upload manager scene, but multiple ones: 
    - Right next to a collection header, *if* the collection is currently uploaded. 
    - In the preview scene. (the one were you can see all assets of a collection in a list). Only available, if you didn't trigger the upload.)

I already recommended putting a button to reach the upload manager in the top right corner of the main scene. @cstiens is against that, she wants it to be in the settings scene. I'll place a button there, but I advise against it. The upload manager is **the** central thing of the app, besides the main scene. It has nothing to do with settings. One needs to be able to reach it from the main scene.

Also, there's always going to be the issue of broken uploads. The user needs to be able to see them. Don't count on auto-retry. We don't auto-retry forever. There's always going to be broken uploads. Period.

Please discuss changes to this without me, as I can not add any more relevant information. Let me know the results.
