### ISSUE TITLE
Connect Your Space: Private Server 

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#8]
The workflow below shows how to connect to a private server the first time a user launches the app.

![oa-connectspace-privateserver](https://user-images.githubusercontent.com/1434597/49390176-ceae1f80-f6ed-11e8-84ae-0728b28c29d6.png)

**Comment by tladesignz** [comment]
I have the following issues with this:

1. "Skip" on the first scene. And what then? And how to get back into this flow, when skipped the first time?

2. "Human Rights Watch" is not something a computer can use to identify a server. "Server Name" on the other hand is rather opaque in terms of what the user actually needs to provide in order to have the app be able to connect. Please clarify!

3. In the current version I have a "subfolder(s)" text field to specify Open Archive's working directory on the server. We can make the user provide that together with the base URL of a WebDAV server, but please note, that Nextcloud doesn't help you with that. Users need to copy/paste text strings together in the correct fashion to have that working. (That's why I provided that text field...) Or will the app have a hardcoded working directory? That will, however, interfere with the server admin's ability to organize stuff on the server.

**Comment by tladesignz** [comment]
Ah, ok. 1) is clarified in issue #10.

**Comment by cstiens** [comment]
Re 3: for subfolders set up on the server, the plan in the design is to handle that in another view. We have the mock-up posted in another ticket. In the home view after you connect the server-- if there are subfolders setup, we would prompt the user to add a project. 

On the dev side, we would need to detect if there are subfolders setup then index them so we can show them as a list.

**Comment by tladesignz** [comment]
> we would prompt the user to add a project.

Sorry, **I** am talking about the URL of a server, potentially containing subfolders, which together comprise the root of where to start. "Project" is some higher level concept. I'm not sure what you mean with it in this context.

Need to talk about this tomorrow.

**Comment by n8fr8** [comment]
We need to add a "Server URL" entry box as well.

**Comment by n8fr8** [comment]
Also add "Default Folder" as an entry box, with the default value of "openarchive" (for now)

**Comment by tladesignz** [comment]
A slightly different version is now implemented.
