### ISSUE TITLE
Reverse animation (slide in) when 'Settings' view opens

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#82]
@tladesignz Can the settings view slide in from the left instead of the right?

**Comment by tladesignz** [comment]
Unfortunately not.
This is the animation which happens, because we're on a navigation stack. (It's just, that the navigation header is hidden in the main scene.)

I can present it modally, than you have 4 options, none of them are from the left. iOS is rather opinionated about this...

https://developer.apple.com/documentation/uikit/uimodaltransitionstyle

**Comment by tladesignz** [comment]
I switched this a while ago to be a popover.
On iPhone, that means it will slide in from the bottom.
On iPad, it's a real popover which is attached to the space icon.

I feel, that's really, how it should be. Animations cannot be chosen, anyway.

So, I'll close this issue.
