### ISSUE TITLE
Switch to back button in Single item view, rather than 'x' (TBD)

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#84]

**Comment by kckthx** [comment]
Swiping through and all actions would work the same, but navigation is different.
'Back' takes you back to the home screen, 'Done' saves all changes made and also goes back to home -- this can help with feeling like info added isn't saved when tapping an 'X'

![OA-Individual Preview](https://user-images.githubusercontent.com/36669955/56382498-2c469280-61dd-11e9-93c6-8f49ba75c207.png)

**Comment by tladesignz** [comment]
Sorry, no "Done" button. This would be inconsistent with Apple UX guidelines: You should always store user changes immediately.

**Comment by kckthx** [comment]
@tladesignz will there be anything in the right corner then?

**Comment by tladesignz** [comment]
@kckthx: Not until you find something you want to put there. :-)

**Comment by kckthx** [comment]
haha well is it against the apply UX guidelines to have 'Done' on the right to close out the view, or is it against guidelines for 'Done' to _save the changes_? 

in other words -- would we still be able to keep it saying 'Done' if we know that 'Done' isn't actually when the metadata is saved -- it just feels more concrete to the user?

One of the reasons we changed this view was because just having an X or Back button felt like it wasn't saved and we wanted the user to feel more confident that their information was saved.

**Comment by tladesignz** [comment]
Apple says: "Though shall always save user input right away!"
So, that's what users should (and through training will) expect, at least when they move back out of the navigation stack. The X may seem a little confusing, but I'm pretty confident that this doesn't count for navigating back and forth through the stack of scenes.

I'm not completely sure (as in: I'm not keen on searching it), if and what Apple says explicitly about having two buttons named differently on the left and right of the navigation header doing the same thing, but I'm pretty positive, they wouldn't like it.

Therefore, as long as you prove me otherwise, I won't implement things like that. Sorry, but that idea brushes completely against my feeling of how it ought to be. :-/ I've never seen something like that, and it feels like a very bad idea.

**Comment by kckthx** [comment]
ok, so just the back arrow on the left and nothing on right then.

**Comment by foundscapes** [comment]
The back arrow does not indicate that the information entered was saved. An example of how this feature is used is in Instagram: when you edit the photo or add information after editing their is always a "done" button (in lower part of screen) or "share" (in the upper right corner) once the media has been edited. The < arrow does not indicate that your actions were saved. 

This decision came straight from our target users who did not feel their metadata was saved and we will likely need to revisit in the future.

**Comment by tladesignz** [comment]
> This decision came straight from our target users who did not feel their metadata was saved and we will likely need to revisit in the future.

Your target users saw an X. And that's indeed confusing, as that sometimes also means "delete". 
That's what you get when you don't stick to Apple design guides and standard UI elements.

That's not the same as the standard scene stack navigation which is operated via the navigation header. This is basically everywhere in iOS and anytime a user makes a change (e.g. Settings app), the change is stored immediately and it is accepted and anticipated, that that's all there is to do.

Some users might still think "oh, was that change stored?" but they'll check a few times and then that's learned. End of story.

**Comment by foundscapes** [comment]
Let's hope it becomes clear.
