### ISSUE TITLE
Fix UI for 'New Project' View

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#85]

**Comment by kckthx** [comment]
I changed the title of the state to just be at the top, instead of feeling like a field to complete. 
@tladesignz is this layout for the fields possible? Currently everything is right justified and it feels strange to me.

![OA-new-project](https://user-images.githubusercontent.com/36669955/56384540-3e76ff80-61e2-11e9-8c1a-c9654764d221.png)

We should also discuss how to handle in UI when adding a browsed project instead of the new one. 

Also, we can currently add a new project from the "Browse" view. I thought we weren't going to allow that?

**Comment by tladesignz** [comment]
> We should also discuss how to handle in UI when adding a browsed project instead of the new one.
> 
> Also, we can currently add a new project from the "Browse" view. I thought we weren't going to allow that?

We had that discussion already with #38. I thought that was finally decided?

**Comment by cstiens** [comment]
> We should also discuss how to handle in UI when adding a browsed project instead of the new one.

@tladesignz This section of the prototype shows the workflow for browsing projects—
https://invis.io/Y6P8RBQ8EX2#/332700000_OA-New-Project

So, in the 'Browse Projects' view—
* Once the user selects a project, it's checked and they tap Done. After tapping done, they are taken to the home view with the project added.
* Also, note, there's no option to 'add a new project' from the Browse project view.

**Comment by foundscapes** [comment]
Need to update this screen so it's more clear - OKT working on UI

**Comment by foundscapes** [comment]
Make sure hint text isn't same as the label for text field

**Comment by tladesignz** [comment]
Ok, so I revisited this issue and made sure to fully understand what you mean. :-) Sorry for the confusion.

I adapted the flow and removed the label, which is actually possible easily.

It looks way more than your linked design now.
Check it out at the next TestFlight!

**Comment by tladesignz** [comment]
I'll close this for now, please re-open, when you want more changes!
