### ISSUE TITLE
Increase the size of the new project '+'

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#86]

**Comment by tladesignz** [comment]
Damn. This is not a string, but an image of yours. When I use a string "+" it doesn't get properly centered vertically, unfortunately.

Can you provide an improved "+" image? Please no borders inside the image and mind the pixel size, the SVG is supposed to render to. The current one is set to 11 x 11 px. It should be 24x24!

**Comment by foundscapes** [comment]
@csteins @kckthx can you send this to him asap? Thanks

**Comment by kckthx** [comment]
https://github.com/OpenArchive/openarchive-assets/blob/master/icons/add-project.svg

**Comment by kckthx** [comment]
that should be the right size let me know if it needs to be bigger

**Comment by tladesignz** [comment]
I replaced it, but it doesn't look bigger to me. Please see for yourself on the next TestFlight with upcoming build 20.

This is the raw SVG file:
https://raw.githubusercontent.com/OpenArchive/openarchive-assets/master/icons/add-project.svg

You can clearly see this line:

```svg
<svg width="21px" height="21px" viewBox="0 0 21 21" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

That's 21 x 21 pixels. It *should* be 24 x 24.

**Comment by kckthx** [comment]
ok, @tladesignz I exported this one larger -- https://github.com/OpenArchive/openarchive-assets/blob/master/icons/add-project-24.svg

**Comment by tladesignz** [comment]
Very nice. Just recognized - There were 2 plus images. Used the wrong one. *ooops*
Anyway, I used the last one now, you can check it out in an upcoming TestFlight and we ca switch to the smaller one, if it actually would be too big.

**Comment by tladesignz** [comment]
Ah, sorry. This was a total misunderstanding. I always thought, it was about the "+" on the "add asset" button in the bottom right corner. Don't know how I could overlook that.

Just checked for the "add project" button: This is very difficult, unfortunately.

I use this Google Material Components `MDCTabBar` class. It's highly opinionated, so I can either use icons and text below, text only or icons only.
So, currently I'm using text only and that "+" sign needs to be a real "+" from the font. So that's the same size as all the text in the project header, which currently is 13 points.

I can increase the font size, but that means, that *everything* in that toolbar will get bigger.

I can remove the toolbar, but that means I need to program my own, which could take some days. A quick search for other tab bars revelead this:

https://uxplanet.org/20-ios-tab-bar-open-source-ui-animation-components-libraries-swift-objective-c-43c0039dff0d

That's also quite some work to choose the best and rework everything for just the size of the plus.

I suggest to reschedule to a later milestone.

**Comment by foundscapes** [comment]
Moved to milestone 5

**Comment by foundscapes** [comment]
In the meantime, can we add "add project" where it is in clickable teal?

**Comment by foundscapes** [comment]
Alternately do what N8 did and have the tab screen say "add new project"

**Comment by foundscapes** [comment]
replace + with "New"

**Comment by foundscapes** [comment]
Bold / italic font

**Comment by tladesignz** [comment]
This thing is really annoying. There's absolutely no wiggle room for styling. One can just define different font styles for the selected item and for unselected ones.
No way to work with icons. Take a lot of space, size can't be controlled.
Same with colors.

Sorry, it's just the "New" or a completely different tab bar.

**Comment by foundscapes** [comment]
@tladesignz annoying, but I think it's ok for now
